### ISSUE TITLE
Remove `sed` command in the formula

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/homebrew-metanorma#3]
In #2 we added the `sed` command:

```ruby
system "sed", "-i", "--", "s/'metanorma-standoc', \"~> 1.0.6\"/'metanorma-standoc', \"1.1.0\"/g", "metanorma-cli.gemspec"
```

We should fix the actual problem in `metanorma-cli` and remove this.

**Comment by ronaldtse** [comment]
@opoudjis it seems that we "fix" the versions in a too stringent way. Can we loosen them so that they don't get so tightly bundled?

**Comment by ronaldtse** [comment]
I think @opoudjis is going to release the gems early next week.

**Comment by CAMOBAP795** [comment]
@ronaldtse done
